spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
#  redis:
#    host: ${REDIS_HOST:10.100.240.124}
#    port: ${REDIS_PORT:16379}
#    jedis:
#      pool:
#        max-wait: 10000
#        max-active: 50
#        max-idle: 30
#        min-idle: 0
#    timeout: 5000
#    password: salesaux

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    prefer-ip-address: true
    ip-address: ${EUREKA_HOST:localhost}
    leaseRenewalIntervalInSeconds: 5
    hostname: wx-service
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9000}/eureka/


# 跨服务数据合并
merge:
  enabled: true
  guavaCacheNumMaxSize: 1000
  guavaCacheRefreshWriteTime: 10 # min
  guavaCacheRefreshThreadPoolSize: 10
  aop: # 启动注解的方式,自动聚合
    enabled: true


# 测试环境
wx:
  ma:
    appid: wx21d554e0be46b50f
    secret: 945f5c0782a17c5130b8c3020c326d97
  cp:
    corpId: ww41012b98245950a2
    agentId: 1000002
    secret: HxrpE6vXOYsVjkkkuCwSxUlERmsKWr20iCBnn14iI4c