server:
  port: 9001

spring:
  application:
    name: springcloud-gate

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9000}/eureka/
  instance:
    prefer-ip-address: true