server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: eureka-server

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:9000}/eureka/
    fetchRegistry: false